/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SlugRouteRouteImport } from './routes/slug/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/slug/index'
import { Route as Router_stateIndexRouteImport } from './routes/router_state/index'
import { Route as QueryIndexRouteImport } from './routes/query/index'
import { Route as ParamsIndexRouteImport } from './routes/params/index'
import { Route as BlockerIndexRouteImport } from './routes/blocker/index'
import { Route as TestNestedRouteImport } from './routes/test.nested'
import { Route as SlugNotificationsRouteImport } from './routes/slug/notifications'
import { Route as SlugSlugRouteImport } from './routes/slug/$slug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as ContextContextRouteRouteImport } from './routes/context/_context/route'
import { Route as ContextContextRouteAIndexRouteImport } from './routes/context/_context/route-a/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/slug',
  path: '/slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const Router_stateIndexRoute = Router_stateIndexRouteImport.update({
  id: '/router_state/',
  path: '/router_state/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueryIndexRoute = QueryIndexRouteImport.update({
  id: '/query/',
  path: '/query/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParamsIndexRoute = ParamsIndexRouteImport.update({
  id: '/params/',
  path: '/params/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockerIndexRoute = BlockerIndexRouteImport.update({
  id: '/blocker/',
  path: '/blocker/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNestedRoute = TestNestedRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => TestRoute,
} as any)
const SlugNotificationsRoute = SlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSlugRoute = SlugSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SlugRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ContextContextRouteRoute = ContextContextRouteRouteImport.update({
  id: '/_context',
  getParentRoute: () => ContextRoute,
} as any)
const ContextContextRouteAIndexRoute =
  ContextContextRouteAIndexRouteImport.update({
    id: '/route-a/',
    path: '/route-a/',
    getParentRoute: () => ContextContextRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slug': typeof SlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/test': typeof TestRouteWithChildren
  '/context': typeof ContextContextRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/slug/$slug': typeof SlugSlugRoute
  '/slug/notifications': typeof SlugNotificationsRoute
  '/test/nested': typeof TestNestedRoute
  '/blocker': typeof BlockerIndexRoute
  '/params': typeof ParamsIndexRoute
  '/query': typeof QueryIndexRoute
  '/router_state': typeof Router_stateIndexRoute
  '/slug/': typeof SlugIndexRoute
  '/context/route-a': typeof ContextContextRouteAIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/test': typeof TestRouteWithChildren
  '/context': typeof ContextContextRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/slug/$slug': typeof SlugSlugRoute
  '/slug/notifications': typeof SlugNotificationsRoute
  '/test/nested': typeof TestNestedRoute
  '/blocker': typeof BlockerIndexRoute
  '/params': typeof ParamsIndexRoute
  '/query': typeof QueryIndexRoute
  '/router_state': typeof Router_stateIndexRoute
  '/slug': typeof SlugIndexRoute
  '/context/route-a': typeof ContextContextRouteAIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/slug': typeof SlugRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/test': typeof TestRouteWithChildren
  '/context/_context': typeof ContextContextRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/slug/$slug': typeof SlugSlugRoute
  '/slug/notifications': typeof SlugNotificationsRoute
  '/test/nested': typeof TestNestedRoute
  '/blocker/': typeof BlockerIndexRoute
  '/params/': typeof ParamsIndexRoute
  '/query/': typeof QueryIndexRoute
  '/router_state/': typeof Router_stateIndexRoute
  '/slug/': typeof SlugIndexRoute
  '/context/_context/route-a/': typeof ContextContextRouteAIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/slug'
    | '/login'
    | '/test'
    | '/context'
    | '/dashboard'
    | '/demo/tanstack-query'
    | '/slug/$slug'
    | '/slug/notifications'
    | '/test/nested'
    | '/blocker'
    | '/params'
    | '/query'
    | '/router_state'
    | '/slug/'
    | '/context/route-a'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/test'
    | '/context'
    | '/dashboard'
    | '/demo/tanstack-query'
    | '/slug/$slug'
    | '/slug/notifications'
    | '/test/nested'
    | '/blocker'
    | '/params'
    | '/query'
    | '/router_state'
    | '/slug'
    | '/context/route-a'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/slug'
    | '/login'
    | '/test'
    | '/context/_context'
    | '/_auth/dashboard'
    | '/demo/tanstack-query'
    | '/slug/$slug'
    | '/slug/notifications'
    | '/test/nested'
    | '/blocker/'
    | '/params/'
    | '/query/'
    | '/router_state/'
    | '/slug/'
    | '/context/_context/route-a/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TestRoute: typeof TestRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  BlockerIndexRoute: typeof BlockerIndexRoute
  ParamsIndexRoute: typeof ParamsIndexRoute
  QueryIndexRoute: typeof QueryIndexRoute
  Router_stateIndexRoute: typeof Router_stateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slug': {
      id: '/slug'
      path: '/slug'
      fullPath: '/slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slug/': {
      id: '/slug/'
      path: '/'
      fullPath: '/slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/router_state/': {
      id: '/router_state/'
      path: '/router_state'
      fullPath: '/router_state'
      preLoaderRoute: typeof Router_stateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/query/': {
      id: '/query/'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof QueryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/params/': {
      id: '/params/'
      path: '/params'
      fullPath: '/params'
      preLoaderRoute: typeof ParamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocker/': {
      id: '/blocker/'
      path: '/blocker'
      fullPath: '/blocker'
      preLoaderRoute: typeof BlockerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/nested': {
      id: '/test/nested'
      path: '/nested'
      fullPath: '/test/nested'
      preLoaderRoute: typeof TestNestedRouteImport
      parentRoute: typeof TestRoute
    }
    '/slug/notifications': {
      id: '/slug/notifications'
      path: '/notifications'
      fullPath: '/slug/notifications'
      preLoaderRoute: typeof SlugNotificationsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/slug/$slug': {
      id: '/slug/$slug'
      path: '/$slug'
      fullPath: '/slug/$slug'
      preLoaderRoute: typeof SlugSlugRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/context/_context': {
      id: '/context/_context'
      path: ''
      fullPath: '/context'
      preLoaderRoute: typeof ContextContextRouteRouteImport
      parentRoute: typeof ContextRoute
    }
    '/context/_context/route-a/': {
      id: '/context/_context/route-a/'
      path: '/route-a'
      fullPath: '/context/route-a'
      preLoaderRoute: typeof ContextContextRouteAIndexRouteImport
      parentRoute: typeof ContextContextRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SlugRouteRouteChildren {
  SlugSlugRoute: typeof SlugSlugRoute
  SlugNotificationsRoute: typeof SlugNotificationsRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugSlugRoute: SlugSlugRoute,
  SlugNotificationsRoute: SlugNotificationsRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface TestRouteChildren {
  TestNestedRoute: typeof TestNestedRoute
}

const TestRouteChildren: TestRouteChildren = {
  TestNestedRoute: TestNestedRoute,
}

const TestRouteWithChildren = TestRoute._addFileChildren(TestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TestRoute: TestRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  BlockerIndexRoute: BlockerIndexRoute,
  ParamsIndexRoute: ParamsIndexRoute,
  QueryIndexRoute: QueryIndexRoute,
  Router_stateIndexRoute: Router_stateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
