/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SlugRouteRouteImport } from './routes/slug/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/slug/index'
import { Route as ParamsIndexRouteImport } from './routes/params/index'
import { Route as TestNestedRouteImport } from './routes/test.nested'
import { Route as SlugNotificationsRouteImport } from './routes/slug/notifications'
import { Route as SlugSlugRouteImport } from './routes/slug/$slug'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/slug',
  path: '/slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const ParamsIndexRoute = ParamsIndexRouteImport.update({
  id: '/params/',
  path: '/params/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNestedRoute = TestNestedRouteImport.update({
  id: '/nested',
  path: '/nested',
  getParentRoute: () => TestRoute,
} as any)
const SlugNotificationsRoute = SlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSlugRoute = SlugSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SlugRouteRoute,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/slug': typeof SlugRouteRouteWithChildren
  '/test': typeof TestRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/slug/$slug': typeof SlugSlugRoute
  '/slug/notifications': typeof SlugNotificationsRoute
  '/test/nested': typeof TestNestedRoute
  '/params': typeof ParamsIndexRoute
  '/slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/slug/$slug': typeof SlugSlugRoute
  '/slug/notifications': typeof SlugNotificationsRoute
  '/test/nested': typeof TestNestedRoute
  '/params': typeof ParamsIndexRoute
  '/slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/slug': typeof SlugRouteRouteWithChildren
  '/test': typeof TestRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/slug/$slug': typeof SlugSlugRoute
  '/slug/notifications': typeof SlugNotificationsRoute
  '/test/nested': typeof TestNestedRoute
  '/params/': typeof ParamsIndexRoute
  '/slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/slug'
    | '/test'
    | '/demo/tanstack-query'
    | '/slug/$slug'
    | '/slug/notifications'
    | '/test/nested'
    | '/params'
    | '/slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/demo/tanstack-query'
    | '/slug/$slug'
    | '/slug/notifications'
    | '/test/nested'
    | '/params'
    | '/slug'
  id:
    | '__root__'
    | '/'
    | '/slug'
    | '/test'
    | '/demo/tanstack-query'
    | '/slug/$slug'
    | '/slug/notifications'
    | '/test/nested'
    | '/params/'
    | '/slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
  TestRoute: typeof TestRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  ParamsIndexRoute: typeof ParamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slug': {
      id: '/slug'
      path: '/slug'
      fullPath: '/slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slug/': {
      id: '/slug/'
      path: '/'
      fullPath: '/slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/params/': {
      id: '/params/'
      path: '/params'
      fullPath: '/params'
      preLoaderRoute: typeof ParamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/nested': {
      id: '/test/nested'
      path: '/nested'
      fullPath: '/test/nested'
      preLoaderRoute: typeof TestNestedRouteImport
      parentRoute: typeof TestRoute
    }
    '/slug/notifications': {
      id: '/slug/notifications'
      path: '/notifications'
      fullPath: '/slug/notifications'
      preLoaderRoute: typeof SlugNotificationsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/slug/$slug': {
      id: '/slug/$slug'
      path: '/$slug'
      fullPath: '/slug/$slug'
      preLoaderRoute: typeof SlugSlugRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SlugRouteRouteChildren {
  SlugSlugRoute: typeof SlugSlugRoute
  SlugNotificationsRoute: typeof SlugNotificationsRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugSlugRoute: SlugSlugRoute,
  SlugNotificationsRoute: SlugNotificationsRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

interface TestRouteChildren {
  TestNestedRoute: typeof TestNestedRoute
}

const TestRouteChildren: TestRouteChildren = {
  TestNestedRoute: TestNestedRoute,
}

const TestRouteWithChildren = TestRoute._addFileChildren(TestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
  TestRoute: TestRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  ParamsIndexRoute: ParamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
